# workflow to run the o2scrap unittest suite

name: Python Tests

on:
  push:
  pull_request:
    branches: [ devel ]
  schedule:
    - cron:  '0 2 * * 6'

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.x, 3.8]
    name: Pylint test (${{ matrix.python_version }})
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt-dev python-dev        
          python -m pip install --upgrade pip
          pip install pylint pylint-exit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: "Pylint folder: o2scrap"
        run: |
          pylint --rcfile=".github/pylintrc" o2_scrap/ || pylint-exit $?
